### ISSUE TITLE
fmt11 migration erred on mamba

### ISSUE THREAD

**Issue by jjerphan** [regro/conda-forge-feedstock-check-solvable#51]
The bot err'ed on mamba for [the fmt 11 migration](https://conda-forge.org/status/migration/?name=fmt11) with the following error:

```
bot error (
bot CI job
): main:
Error running check-solvable in container - error ValueError raised:
"Very odd pinning: pin_compatible('fmt',max_pin='x.x')! Package fmt not found in host {}!"
```

[`fmt` is indeed only present in the `host` section of `libmamba`](https://github.com/conda-forge/mamba-feedstock/blob/92732188178c7de6cd748d30bff5185d9c3d8a39/recipe/meta.yaml#L47) (and `libmambapy`'s) and not in `mamba`, because `mamba` does not depend on it.

I will open a PR to perform the migration manually.

This was previously discussed with @h-vetinari which invited me to report this issue.

**Comment by h-vetinari** [comment]
> [`fmt` is indeed only present in the `host` section of `libmamba`](https://github.com/conda-forge/mamba-feedstock/blob/92732188178c7de6cd748d30bff5185d9c3d8a39/recipe/meta.yaml#L47)

This is not correct, see line 55. However the bot is also not correct, in that it diagnoses a use of `pin_compatible` without a host dependency, yet the host dependency is there.

There are a bunch of superfluous run-requirements (already covered by run-exports), but those are benign, and certainly shouldn't fail the bot, which is why I suggested raising an issue.

**Comment by jjerphan** [comment]
I should have been clearer: I meant to highlight that the relevant host sections were `libmamba`'s and `libmambapy`'s, not that other pins were not present.

**Comment by beckermr** [comment]
Even weirder is that if you dig directly into the bot ci job, you'll see an actual solver error and some other random missing host package. I'm not actually sure what the error string the bot was supposed to report was.

**Comment by beckermr** [comment]
Looks like the pr failed which means I think maybe the error string on the status page is wrong?

**Comment by jjerphan** [comment]
We need the changes upstream to be part of a new release for this PR to pass.
